### ISSUE TITLE
Error executing in arm64

### ISSUE THREAD

**Issue by giovannicandido** [cloudnative-pg/postgis-containers#29]
Running container versions 14 and 15. The follow error happens:

Defaulted container "initdb" out of: initdb, bootstrap-controller (init)
{"level":"info","ts":1676438529.033376,"msg":"Creating new data directory","logging_pod":"infra-db-1","pgdata":"/var/lib/postgresql/data/pgdata","initDbOptions":["--username","postgres","-D","/var/lib/postgresql/data/pgdata","--encoding=UTF8","--lc-collate=C","--lc-ctype=C"]}
{"level":"error","ts":1676438529.051798,"msg":"Error while bootstrapping data directory","logging_pod":"infra-db-1","error":"error while creating the PostgreSQL instance: fork/exec /usr/lib/postgresql/14/bin/initdb: exec format error","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:134\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func1\n\tinternal/cmd/manager/instance/initdb/cmd.go:94\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/proc.go:250"}
Error: error while creating the PostgreSQL instance: fork/exec /usr/lib/postgresql/14/bin/initdb: exec format error

Its working ok with images: ghcr.io/cloudnative-pg/postgresql:15.0

**Comment by giovannicandido** [comment]
Looks like the base image has not compiled with ARM support.
I will open a issue in the base image repo

**Comment by giovannicandido** [comment]
A issue already exist: https://github.com/postgis/docker-postgis/issues/216 but is a long time without a solution.
In my case I will need to do a custom build, because I need it more quickly

**Comment by sxd** [comment]
Closing this since it's not an issue that can be fixed in our side
