### ISSUE TITLE
Container images do not report the PostGIS version

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/postgis-containers#9]
Currently, the registry contains only images that report just the PostgreSQL version. For example:

```
ghcr.io/cloudnative-pg/postgis:14-3
```

However, the official ones report the combo PostgreSQL + PostGIS, see https://hub.docker.com/r/postgis/postgis.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/182151/183653342-4b67ee17-832d-45c9-adb4-c8f47fe337c8.png">

While I understand we might not want to expose the PostGIS version in the name of the image, it would be great at least to have that in the form of tags.

**Comment by gbartolini** [comment]
Ideally, `ghcr.io/cloudnative-pg/postgis:14-3` should be named `ghcr.io/cloudnative-pg/postgis:14-3.2-3`. However, I am not sure this works as I suspect this can interfere with the automated detection of the Postgres version from the image name. Worth exploring.

**Comment by hh24k** [comment]
See the latest build-out image of postgis-testing --> https://github.com/cloudnative-pg/postgis-containers/pkgs/container/postgis-testing ... Now we have image tag as `$postgresMajorVersion-$postgisMajorVersion-$postgisMiniorVersion-$releaseNumber`

<img width="728" alt="Screen Shot 2022-08-24 at 11 21 34" src="https://user-images.githubusercontent.com/13548039/186318226-c09f6752-708a-4272-b6e5-050a9eb196f9.png">
